[package]
name = "dot-calendar"
version = "0.3.14"
edition = "2021"
description = "A quiet, native Windows calendar for Your dot"
license = "MIT"
repository = "https://github.com/7065616b/dot-calendar"
homepage = "https://7065616b.github.io/dot-calendar/"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ureq = { version = "2.12", default-features = false, features = ["json", "native-tls"] }
sha2 = "0.10"
base64 = "0.22"
getrandom = "0.2"
chrono = { version = "0.4", default-features = false, features = ["std"] }
rs-klc = "0.2"
windows-sys = { version = "0.61", features = [
  "Win32_Foundation", "Win32_Graphics_Gdi", "Win32_Graphics_Dwm",
  "Win32_Storage_FileSystem", "Win32_Security", "Win32_System_Threading",
  "Win32_System_SystemInformation", "Win32_System_LibraryLoader",
  "Win32_System_Console", "Win32_UI_WindowsAndMessaging", "Win32_UI_Controls",
  "Win32_System_DataExchange", "Win32_System_Memory",
  "Win32_UI_HiDpi", "Win32_UI_Input_KeyboardAndMouse",
  "Win32_Security_Cryptography", "Win32_UI_Shell",
  "Win32_UI_Controls_Dialogs", "Win32_System_Registry", "Win32_Storage_Xps"
] }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
panic = "abort"
